#route_name:
#    path: /
#    controller: App\Controller\ControllerFileClass::methodName
index:
    path: /
    controller: App\Controller\Homepage\DefaultController:index

### user logic

user_login:
    path: /login
    controller: App\Controller\UserController:login

user_logout:
    path: /logout
    controller: App\Controller\UserController:logout

user_signup:
    path: /signup
    controller: App\Controller\UserController:signup

### other

new_user:
    path: /user/new
    controller: App\Controller\UserController:new

sample_user:
    path: /user/new_sample
    controller: App\Controller\UserController:new_sample