#route_name:
#    path: /
#    controller: App\Controller\ControllerFileClass::methodName
index:
    path: /
    controller: App\Controller\Homepage\DefaultController:index

### user logic

user_login:
    path: /login
    controller: App\Controller\UserController:login

user_logout:
    path: /logout
    controller: App\Controller\UserController:logout

user_signup:
    path: /signup
    controller: App\Controller\UserController:signup

### user pages

user_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController:dashboard

user_updates:
    path: /updates
    controller: App\Controller\DashboardController:updates

### other
