#route_name:
#    path: /
#    controller: App\Controller\ControllerFileClass::methodName
index:
    path: /
    controller: App\Controller\Homepage\DefaultController:index

### user logic

user_login:
    path: /login
    controller: App\Controller\UserController:login

user_logout:
    path: /logout
    controller: App\Controller\UserController:logout

user_signup:
    path: /signup
    controller: App\Controller\UserController:signup

### user pages

user_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController:dashboard

user_updates:
    path: /updates
    controller: App\Controller\DashboardController:updates

### inboxes

inbox_dashboard:
    path: /dashboard/inbox/{inbox_id}
    controller: App\Controller\DashboardController:dashboard

inbox_updates:
    path: /updates/inbox/{inbox_id}
    controller: App\Controller\DashboardController:updates

inbox_enter:
    path: /dashboard/inbox/user/{user_id}
    controller: App\Controller\InboxController:enter

add_message:
    path: /add/message
    controller: App\Controller\InboxController:createMessage

# add message to inbox
# add user to inbox (create inbox if doesn't exist)
# see messages (seen = true)
# get messages
# get inboxes?

### groups

group_dashboard:
    path: /dashboard/group/{group_id}
    controller: App\Controller\DashboardController:dashboard

group_updates:
    path: /updates/group/{group_id}
    controller: App\Controller\DashboardController:updates

# create group
# add post
# add comment to post
# add notification to user
# add add user to group
# see notifications (seen = true)
# get posts/comments
# get groups?

### other
