#route_name:
#    path: /
#    controller: App\Controller\ControllerFileClass::methodName
index:
    path: /
    controller: App\Controller\Homepage\DefaultController:index

new_user:
    path: /user/new
    controller: App\Controller\UserController:new

sample_user:
    path: /user/new_sample
    controller: App\Controller\UserController:new_sample